version: '2.2'
services:
    cypresstestdocker:
        image: cypresstestdocker
        environment:
            - URI_ROOT=yn.test
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
volumes:
  node_modules:


