version: 2

# build job parameters as a template
defaults: &defaults
  working_directory: ~/app
  docker:
    # the Docker image with Cypress dependencies
    - image: cypress/base:8
      environment:
        ## this enables colors in the output
        TERM: xterm

defaultsTestRequires: &defaultsTestRequires
          requires:
            - build
            - scan

# test job parameters as a template
defaultsTest: &defaultsTest
    steps:
      - attach_workspace:
          at: ~/            
      - run:
          name: Running E2E tests
          when: on_success
          command: make test-qa       
      - store_test_results:
          path: cypress/reports
      - store_artifacts:
          path: cypress/reports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - run:
          name: Slack Custom Reporting
          when: always
          command: |
            cd .circleci
            chmod +x slack-alert.sh
            ./slack-alert.sh
            
jobs:
  build:
    <<: *defaults        
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - app

  scan:
      parameters:
      is-pull-request:
        type: boolean
        default: true
    <<: *defaults        
    steps:
      - when:
          condition: << parameters.is-pull-request >>
          steps:
            - attach_workspace:
                at: ~/                   
            - run:
                name: Sonarqube if Pull Request
                command: |
                  cd .circleci
                  chmod +x sonar-scanner-on-pr.sh
                  ./sonar-scanner-on-pr.sh    
      
  test1:
    <<: *defaults
    <<: *defaultsTest
    
  test2:
    <<: *defaults
    <<: *defaultsTest

  test3:
    <<: *defaults
    <<: *defaultsTest
    
  test4:
    <<: *defaults
    <<: *defaultsTest

  test5:
    <<: *defaults
    <<: *defaultsTest
    
  test6:
    <<: *defaults
    <<: *defaultsTest

  test7:
    <<: *defaults
    <<: *defaultsTest
    
  test8:
    <<: *defaults
    <<: *defaultsTest

workflows:
  version: 2
  build-scan-test:
    jobs:
      - build
      - scan:
          requires:
            - build
          filters:  
            branches:
              ignore: 
                - master
      - test1:
          <<: *defaultsTestRequires
      - test2:
          <<: *defaultsTestRequires
      - test3:
          <<: *defaultsTestRequires
      - test4:
          <<: *defaultsTestRequires          
      - test5:
          <<: *defaultsTestRequires          
      - test6:
          <<: *defaultsTestRequires
      - test7:
          <<: *defaultsTestRequires
      - test8:
          <<: *defaultsTestRequires


